test: # test app instance
  build: ../../ # relative path to source root
  dockerfile: docker/dev/Dockerfile
  volumes_from: # source volume to attach with the container
    - cache
  links:
    - db # add @db to container /etc/hosts
  environment:
    APPNAME_ENV: 'dev'
    MYSQL_HOST: db # match with the db app name
    MYSQL_USER: root
    MYSQL_PASS: root
    TEST_OUTPUT_DIR: /reports

agent:
  image: chenglongzq/ansible
  volumes:
    - ../ansible/playbooks/probe.yml:/ansible/site.yml # default lookup dir by ansible-playbook
  links:
    - db # stop database before agent starts
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"
  #  command: ["probe.yml"]

  # stop all
  # $ docker-compose rm -f
  # start agent
  # $ docker-compose up agent
  # start docker-compose up test
  # ... all happy ...

db:
  image: mysql:5.6
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

cache:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - /tmp/cache:/cache
  entrypoint: "true"

  # docker run --name cache -v /tmp/cache:/cache --entrypoint "true" <tag>
